!1- Indexing 

In [3]:
import numpy as np 

In [4]:
#a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [13]:
a.shape
a 


array([1, 2, 3])

In [14]:
a.dtype

dtype('int32')

In [5]:
#b = np.array([[5.2,8.6,.6],[7.5, 5.6, 9.1]])
b

array([[5.2, 8.6, 0.6],
       [7.5, 5.6, 9.1]])

In [6]:
b.ndim #dimension

2

In [16]:
b.shape #shape




(2, 3)

In [15]:
b.dtype


dtype('float64')

In [18]:
a.nbytes

12

In [17]:
a.itemsize

4

In [28]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [23]:
a.shape

(2, 7)

In [24]:
# get a specific elemtn[r, c]
a[1, 5]

13

In [25]:
# get  a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
#get specific column
a[:, 2]

array([ 3, 10])

In [30]:
#[startindex:endndex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [33]:
a[1, 5] = 20
a

a[:, 2] = [1, 6]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  6, 11, 12, 20, 14]])

In [39]:
#3d example
b = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
#get specific element (go outside in)
b[0,1,1]


4

In [41]:
b[:,1,:]


array([[3, 4],
       [7, 8]])

In [44]:
#replace 
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

!2 - Initializing all sorts of arrays 


In [50]:
# all zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
#all 1s matrix
np.ones((2,4,3))


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
#any other number
np.full((2,2), 101)

array([[101, 101],
       [101, 101]])

In [57]:
#random decimnal numbers
np.random.rand(4,2,5)

array([[[0.66003132, 0.67997672, 0.11401733, 0.48531308, 0.543071  ],
        [0.82109969, 0.80100984, 0.1054749 , 0.64254414, 0.53851338]],

       [[0.96272896, 0.65096747, 0.19005093, 0.8080846 , 0.32950727],
        [0.37419927, 0.77688827, 0.22649609, 0.961513  , 0.62938259]],

       [[0.45024119, 0.79845516, 0.8515853 , 0.06539458, 0.3679134 ],
        [0.4705702 , 0.01700226, 0.45227575, 0.50498669, 0.77296248]],

       [[0.73205088, 0.55337016, 0.85523547, 0.98053494, 0.62516343],
        [0.86819819, 0.94193306, 0.83095118, 0.15662434, 0.47486343]]])

In [97]:
np.random.randint(8, size=(3,3))

array([[3, 1, 5],
       [0, 4, 4],
       [1, 1, 2]])

In [98]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
#repeating an array 
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
r1


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

example problem

In [115]:
output = np.ones((5, 5))
#print(output)

z = np.zeros((3,3))
z[1,1] = 9
#print(z)

output[1:4,1:4] = z
print(output)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
