In [5]:
import numpy as np

In [2]:
mylist = [1,2,3]


In [3]:
type(mylist)

list

In [6]:
np.array(mylist)

array([1, 2, 3])

In [7]:
myarr = np.array(mylist)

In [8]:
myarr

array([1, 2, 3])

In [9]:
type(myarr)

numpy.ndarray

In [10]:
my_matrix = [[1,2,3], [4,5,6] ,[7,8,9]]

In [11]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,44,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((4,6))# keep in mind the idea that shaped are defined first by number of rows then coulmns


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((9,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [23]:
np.eye(5)#identity matrix of the diagonal matrixb

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.random.rand(1)

array([0.88941049])

In [42]:
np.random.rand(5, 6)

array([[0.34713744, 0.11166798, 0.43570251, 0.63293309, 0.62386465,
        0.38179833],
       [0.96358319, 0.30294479, 0.55409739, 0.88749101, 0.96098309,
        0.25811613],
       [0.84137344, 0.8116336 , 0.35407732, 0.10664888, 0.59211351,
        0.34278394],
       [0.48055958, 0.45276371, 0.57156678, 0.24976079, 0.19970081,
        0.31678152],
       [0.19680367, 0.2986471 , 0.43372936, 0.51968081, 0.6522819 ,
        0.45245034]])

In [44]:
np.random.randint(0, 100,(5,6))

array([[79, 96, 43, 37, 74, 95],
       [57, 73, 97, 67, 54, 60],
       [68, 11, 37, 34, 82, 67],
       [45, 29, 59, 86, 28, 34],
       [38, 75, 40, 21, 24, 85]])

In [47]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [49]:
arr = np.arange(0,25)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
ranarr = np.random.randint(0,101,10)


In [52]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [54]:
ranarr.max()


99

In [55]:
ranarr.argmax()

5

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
arr.shape

(25,)

In [59]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr.shape

(5, 5)

Indexing and selection numpy lec 3 


In [3]:
import numpy as np 

In [4]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1: 5]

array([1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

numpy array differs from nomral python list as they have the ability to brodcast in list elements


* Indexing and selection:
-

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:4] =  100 #broadcasting
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr = arr[0:5]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [20]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr[:] = 99


In [21]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

it means using broadcasting would change the og list everytime 


In [24]:
arr_copy = arr.copy()



In [25]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [27]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d.shape

(3, 3)

In [30]:
arr_2d[0]

array([ 5, 10, 15])

In [31]:
arr_2d[2]

array([35, 40, 45])

In [32]:
arr_2d[1,1]

25

In [33]:
arr_2d[0,2]

15

In [34]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [36]:
arr_2d[:2,1:]# this is called slicing of array

array([[10, 15],
       [25, 30]])

In [37]:
#conditional selection
arr = np.arange(1,11)

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [40]:
bool_arr = arr>4



In [41]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

NUmpy operations 

In [43]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [46]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [48]:
arr / arr

C:\Users\daich\AppData\Local\Temp\ipykernel_7552\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [49]:
1 / arr

C:\Users\daich\AppData\Local\Temp\ipykernel_7552\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [50]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [51]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [52]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [53]:
np.log(arr)

C:\Users\daich\AppData\Local\Temp\ipykernel_7552\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr.sum()


45

In [63]:
arr.sum()

45

In [65]:
arr.mean()


4.5

In [67]:
arr.max()

9

In [71]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
arr2d.shape

(5, 5)

In [75]:
arr2d.sum()

300

In [76]:
arr2d.sum(axis=0)#accross the rows

array([50, 55, 60, 65, 70])

In [77]:
arr2d.sum(axis=1)#accross the coulamns

array([ 10,  35,  60,  85, 110])